version: '3.7'
services:
  orientdb:
    image: orientdb:latest
    ports:
      - "2424:2424"
      - "2480:2480"
    environment:
      ORIENTDB_ROOT_PASSWORD: 'orientdb'
    volumes:
      - orientdb_config:/opt/orientdb/config
      - orientdb_databases:/opt/orientdb/databases
      - orientdb_backup:/opt/orientdb/backup
volumes:
  orientdb_config:
    driver: local
  orientdb_databases:
    driver: local
  orientdb_backup:
    driver: local